### ISSUE TITLE
REQUEST INFO CHANGE TRACKER UI

### ISSUE THREAD

**Issue by jusegoram** [jusegoram/angular-synergy-hrms#1]
**REQUEST INFO CHANGE TRACKER UI REQUIREMENTS:**
* required fields must have 'Validators.required'

REQUIRED FIELDS:
- [x] mat-checkbox for each information section. (Ex. Main Info, Company Info, Personal Info, Position Info. )
- [x] text area for a brief description about the issue. 

REQUIRED BUTTONS: 
- [x] cancel button
- [x] send tracker button
