### ISSUE TITLE
TRANSFER TRACKER UI 

### ISSUE THREAD

**Issue by jusegoram** [jusegoram/angular-synergy-hrms#2]
**TRANSFER TRACKER UI REQUIREMENTS:**
 * Required fields must have 'Validators.required'.
* Signatures must be stored in base64 to allow reconstructing images. 

**REQUIRED FIELDS:**
- [x] old client and campaign (readonly) confirmation
- [x] new client and campaign mat-select. 
- [x] effective date.
- [x] manager signature.

**REQUIRED BUTTONS:**
- [x] cancel.
- [x] send tracker.

**REQUIREMENTS:** 
- [x] should NOT allow empty tracker submission.
